# Eleman İşlemleri

In [1]:
import pandas as pd
import numpy as np
a = np.array([15,46,777,88,95])
seri = pd.Series(a)
seri

0     15
1     46
2    777
3     88
4     95
dtype: int64

In [2]:
seri[0]

np.int64(15)

In [3]:
seri[0:3]

0     15
1     46
2    777
dtype: int64

In [4]:
seri = pd.Series([11,55,34,89], index = ["reg", "loj", "cart", "rf"])

In [5]:
seri

reg     11
loj     55
cart    34
rf      89
dtype: int64

In [6]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [7]:
seri.keys

<bound method Series.keys of reg     11
loj     55
cart    34
rf      89
dtype: int64>

In [8]:
list(seri.items())

[('reg', 11), ('loj', 55), ('cart', 34), ('rf', 89)]

In [9]:
seri.values

array([11, 55, 34, 89])

In [10]:
# eleman sorgulama

In [11]:
"reg" in seri

True

In [12]:
"a" in seri

False

In [13]:
seri["reg"]

np.int64(11)

In [14]:
# fancy eleman

In [15]:
seri[["reg", "rf"]]

reg    11
rf     89
dtype: int64

In [16]:
seri["reg"] = 44

In [17]:
seri

reg     44
loj     55
cart    34
rf      89
dtype: int64

In [18]:
seri["reg" : "loj"]

reg    44
loj    55
dtype: int64

In [19]:
# Pandas Dataframe Oluşturma

In [20]:
import pandas as pd

In [21]:
l = [1,16,77,89,101]

In [22]:
pd.DataFrame(l, columns = ["Degisken_ismi"])

Degisken_ismi
0              1
1             16
2             77
3             89
4            101

In [23]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [25]:
# df isimlendirme

In [26]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [27]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [28]:
df.columns = ("deg1", "deg2", "deg3")
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [31]:
df.shape

(3, 3)

In [32]:
df.ndim

2

In [33]:
df.size

9

In [34]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
type(df.values)

numpy.ndarray

In [36]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [37]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [38]:
a = np.array([1,3,5,7,9])

In [39]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     3
2     5
3     7
4     9

In [40]:
# sozluk üzerinden dataframe oluşturma

In [41]:
from numpy import random
s1 = random.randint(10, size = 5)
s2 = random.randint(10, size = 5)
s3 = random.randint(10, size = 5)

In [42]:
sozluk = {"var1" : s1, "var2" : s2, "var3" : s3}

In [43]:
sozluk

{'var1': array([7, 1, 1, 7, 2], dtype=int32),
 'var2': array([7, 2, 1, 5, 2], dtype=int32),
 'var3': array([1, 4, 1, 8, 8], dtype=int32)}

In [44]:
import pandas as pd
df = pd.DataFrame(sozluk)

In [45]:
df

var1  var2  var3
0     7     7     1
1     1     2     4
2     1     1     1
3     7     5     8
4     2     2     8

In [46]:
df[0:1]

var1  var2  var3
0     7     7     1

In [47]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [48]:
df.index = ["a", "b", "c", "d", "e"]

In [49]:
df

var1  var2  var3
a     7     7     1
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [50]:
df["c":"e"] 

var1  var2  var3
c     1     1     1
d     7     5     8
e     2     2     8

In [51]:
#silme

In [52]:
df.drop("a", axis = 0)

var1  var2  var3
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [53]:
#kalıcı olarak silmek için

In [54]:
df.drop("a", axis = 0, inplace = True)

In [55]:
df

var1  var2  var3
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [56]:
#fancy index ile silme işlemi

In [57]:
l = ["b", "c"]

In [58]:
df.drop(l, axis = 0)

var1  var2  var3
d     7     5     8
e     2     2     8

In [59]:
#değişkenler için

In [60]:
df

var1  var2  var3
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [61]:
"var1" in df

True

In [62]:
l = ["var1", "var4","var3"]

In [63]:
for i in l:
    print(i in df)

True
False
True


In [64]:
df["var4"] = df["var1"] / df["var2"]

In [65]:
df

var1  var2  var3  var4
b     1     2     4   0.5
c     1     1     1   1.0
d     7     5     8   1.4
e     2     2     8   1.0

In [66]:
#değişken silmek

In [67]:
df.drop("var4", axis = 1)

var1  var2  var3
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [68]:
df

var1  var2  var3  var4
b     1     2     4   0.5
c     1     1     1   1.0
d     7     5     8   1.4
e     2     2     8   1.0

In [69]:
df.drop("var4", axis = 1, inplace = True)

In [70]:
df

var1  var2  var3
b     1     2     4
c     1     1     1
d     7     5     8
e     2     2     8

In [71]:
#fancy index ile

In [72]:
l = ["var1", "var2"]

In [73]:
df.drop(l, axis = 1)

var3
b     4
c     1
d     8
e     8