# NumPy Dizisi Oluşturmak 🚀

## NumPy ndarray nesnesi oluşturmak 🧠	

ℹ️	*NumPy array'ler ile çalışmak için kullanılır.Numpy'daki array nesnesi **ndarray** olarak adlandırılır.*<br>
ℹ️	*Numpy **ndarray** nesnesi oluşturmak için **array()** fonksiyonunu çağırırız:*<br>

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


📌 ***type()** : Python'daki bu yerleşik fonksiyon bize içerisine geçirdiğimiz nesnenin tipini döndürür.Üstteki örnekte olduğu gibi ndarray nesnesinin tipini bize 'numpy.ndarray' olarak döndürdü.*

ℹ️ *ndarray nesnesi oluştururken, **array()** fonksiyonu içerisine liste,tuple veya herhangi bir dizi benzeri nesneyi input olarak verebiliriz.Fonksiyon verilen input'u ndarray nesnesine dönüştürecektir:*

In [2]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Array'lerde Boyut 🧠	

ℹ️	*Dizilerde boyut,dizi derinliğinin bir seviyesidir(İç içe diziler):*

📌	*iç içe diziler : İçerisinde dizileri eleman olarak barındıran diziler.*

## 0 Boyutlu Diziler 🧠	

ℹ️	*0-D diziler ya da skalerler,dizi içerisindeki elemanların kendisidir.Yani her eleman aslında 0 boyutlu bir dizi oluyor.*

In [3]:
import numpy as np
arr = np.array(50)
print(arr)

50


## 1 Boyutlu Diziler 🧠	

ℹ️  *Elemanları 0 boyutlu dizilerden oluşan dizilerdir.Tek boyutlu veya 1 boyutlu dizi olarak adlandırılır.*<br>
ℹ️  *En yaygın ve basit dizilerdir.*<br>

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2 Boyutlu Diziler 🧠	

ℹ️	*Elemanları 1 boyutlu dizilerden oluşan dizilerdir.*<br>
ℹ️	*Genellikle matrisleri ve 2'nci dereceden tensörleri temsil etmek için kullanılırlar*.<br>

📌	 ***Tensör**: Skalerler,vektörler veya matrisler gibi fiziksel özellikleri tanımlamak için kullanılan matematiksel nesnelerdir.Bir skaler sıfırıncı dereceden bir tensör,bir vektör birinci dereceden tensördür.* 

📌 *NumPy içerisinde numpy.mat adlı matrix üzerinde çeşitli operasyonlar yapabildiğimiz bir modüle sahiptir.*

*Örnek olarak sırasıyla 1,2,3 ve 4,5,6 elemanlarını içeren, 2 tane dizi elemanından oluşan 2 boyutlu bir dizi oluşturalım:*

In [5]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


*Yukarıdaki çıktı 2x3'lük bir matristir.*

## 3 Boyutlu Diziler 🧠	

ℹ️	*İçerisinde eleman olarak 2 boyutlu dizileri(matris) içeren diziler 3 boyutlu dizi adını alır*<br>
ℹ️	*Üçüncü dereceden tensörleri temsil etmek için sıkça kullanılır.*

*İçerisinde 2 boyutlu iki tane dizi içeren 3 boyutlu bir dizi oluşturalım.Her iki matrisin elemanları 1,2,3 ve 4,5,6 olsun.:*

In [6]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


*Yukarıdaki çıktıyı detaylıca inceleyelim.3 boyutlu dizimizin 0'ncı index'inde 2x3'lük bir matris,1'inci index'inde yine 2x3'lük bir matris vardır.*

# Boyut Sayısını Kontrol Etmek ! 🔥

In [7]:
import numpy as np

arr0 = np.array(55)
arr1 = np.array([2,3,5,6])
arr2 = np.array([[1,3,5], [7,8,9]])
arr3 = np.array([[[1,2,4],[5,9,11]], [[3,8,6], [9,11,15]]])
print("arr0 dizisinin boyutu : " + str(np.ndim(arr0)))
print("arr1 dizisinin boyutu : " + str(np.ndim(arr1)))
print("arr2 dizisinin boyutu : " + str(np.ndim(arr2)))
print("arr3 dizisinin boyutu : " + str(np.ndim(arr3)))

arr0 dizisinin boyutu : 0
arr1 dizisinin boyutu : 1
arr2 dizisinin boyutu : 2
arr3 dizisinin boyutu : 3


# Yüksek Boyutlu Diziler 🧠	

📌 *Bir dizi çok yüksek sayıda boyuta sahip olabilir.Bunu parametre olarak dizi oluştururken argüman olarak verebiliriz.*

In [8]:
import numpy as np
arr = np.array([10,20,30,40,50], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[10 20 30 40 50]]]]]
5


🔍*Yukarıdaki çıktıyı inceleyelim:*<br>
   *En içteki boyut(yani 5'inci boyut),içerisinde 4 eleman barındıyor ve bu her bir eleman sıfır boyutlu bir dizi.*<br>
   *4'üncü boyut, içerisinde 1 elemandan oluşan bir vektör içerir.*<br>
   *3'üncü boyut, içerisinde bir matris ve bir vektör barındırıyor.*<br>
   *2'nci boyut, içerisinde 3 boyutlu bir dizi barındırıyor.*<br>
   *Son olarak 1'nci, boyut içerisinde 4 boyutlu bir dizi barındırıyor. Kafa karıştırıcı ama üzerinde durunca gayet anlaşılabilir olduğunu       görebilirsiniz.*