## NumPy'da Array Dilimleme (Array Slicing) 🚀	

## Dizi Dilimleme 🧠	

ℹ️  *Python'da dilimleme; verilen bir indeks değerinden diğer indeks değerine kadarki elemanları alma işlemidir.*<br>
ℹ️  *İndeks yerine dilimlemeyi şu şekilde yapıyoruz: **[start:end]***<br>
ℹ️  *Ayrıca adım sayısını da tanımlayabiliriz: **[start:end:step]***<br>
ℹ️  *Başlangıç değeri(start) varsayılan olarak 0'dır.*<br>
ℹ️  *Bitiş(end) varsayılan olarak o boyuttaki dizi uzunluğu olarak kabul edilir.*<br>
ℹ️  *Adım sayısı(step) varsayılan olarak 1'dir.*

*index 1'den index 5'e kadar dilimleme işlemi yapalım:*

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


⚠️ *Başlangıç değeri sonuca dahildir(inclusive).Bitiş değeri sonuca dahil değildir(exclusive).*<br>

*4'üncü indeks değerinden dizinin sonuna kadar dilimleme işlemi yapalım:*

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


## Negatif Dilimleme (Negative Slicing) 🧠	

*Dizinin sonundan bir elemana erişmek istediğimizde - operatörünü kullanırız.*<br>

*Sondan 3'üncü indeks elemanından sondan 1'inci elemana kadar slicing işlemi:*

In [3]:
import numpy as np
arr = np.array([3,4,5,6,7,9,10,11])
print(arr[-3:-1])

[ 9 10]


## STEP 🧠	

***step** değerini slicing işlemini kaçar kaçar yapacağını belirtmek için kullanırız*.

*1'inci indeks elemanı ile 5'inci indeks elemanı arasındaki bütün elemanları 2'şer 2'şer atlayarak döndür:*

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5:2])

[2 4]


*Bütün diziyi 2'şer 2'şer atlayarak dönder:*

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::2])

[1 3 5 7 9]


## 2 Boyutlu Array'lerde Slicing 🔥	

*2'nci dizi elemanından,1'inci index değerinden 4'üncü index değerine kadar olan elemanlara slicing işlemi:*

In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


⚠️ *İkinci elemanın([6,7,8,9,10]) index değerinin 1 olduğunu unutmayın*.

*Her iki elemandan 2'nci index elemanlarına slicing işlemi:*

In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0:2,2])


[3 7]


*Her iki elemandan,1'inci index değerinden 4'üncü index değeri(exclusive) arasındaki elemanları dilimle:*

In [8]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0:2,1:4])

[[2 3 4]
 [6 7 8]]
