## NumPy'da Veri Tipleri 🚀

## Python'da Veri Tipleri 🧠	

ℹ️	*Python'da varsayılan olarak bulunan veri tipleri :*

***Strings:** Metin verisini temsil etmek için kullanılır.Metin tırnak işareti içerisinde verilir.Ör:"Python"*<br>
***integer:** İnteger sayıların temsilinde kullanılır.Ör:1,2,3,-1,-2,-3*<br>
***float:** Gerçel sayıları temsil etmek için kullanılır.Ör:3.41,77.88*<br>
***boolean:** True ve False temsilinde kullanılır.*<br>
***complex:** Karmaşık sayıların temsilinde kullanılır.Ör: 2+3j,4+9j*

## NumPy'da Veri Tipleri 🧠	

ℹ️	*Numpy ekstra veri tiplerine sahiptir,ve bu veri tipleri bir harflik karakterler ile temsil edilirler.*<br>
ℹ️	*Örneğin integer'lar için **i**,işaretsiz integer'lar için **u** vs.*

ℹ️	*Numpy'daki veri tipleri ve bu veri tiplerinin temsil edildiği karakterler aşağıdaki listedeki gibidir:*

**i** - *integer*<br>
**b** - *boolean*<br>
**u** - *unsigned integer*<br>
**f** - *float*<br>
**c** - *complex float*<br>
**m** - *timedelta*<br>
**M** - *datetime*<br>
**O** - *object*<br>
**S** - *string*<br>
**U** - *unicode string*<br>
**V** - *fixed chunk of memory for other type ( void )*

## Bir Dizinin Veri Tipini Kontrol Etmek 🧠	

ℹ️	*Numpy dizi nesnesi **dtype** adında dizinin veri tipini döndüren bir özelliğe sahiptir:*<br>

In [1]:
# Bir dizi nesnesinin tipini sorgulama
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [2]:
# Birden fazla string ifade içeren dizinin veri tipini sorgulama
import numpy as np
arr = np.array(['Python', 'R', 'SQLite'])
print(arr.dtype)

<U6


## Önceden Tanımlanmış Veri Tipi ile Dizi Nesnesi Oluşturmak 🧠	

ℹ️	*Dizi oluşturmak için **array()** fonksiyonunu kullanırız.İsteğe bağlı olarak argüman alabilir*<br>
ℹ️	***dtype** dizi nesnelerinin beklenen veri tipinin özelliğini tanımlamamızı sağlar.*

In [3]:
#String veri tipinde dizi nesnesi tanımlama
import numpy as np
arr = np.array([2,3,4,5], dtype = 'S')
print(arr)
print(arr.dtype)

[b'2' b'3' b'4' b'5']
|S1


⚠️	***i**,**u**,**f**,**s** ve **U** için boyut da tanımlanabilir.*

In [4]:
# Her biri 4 byte alan kaplayan integer türünde dizi
import numpy as np
arr = np.array([10,20,30,40,50], dtype = 'i4')
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int32


📌	*Ya bir değer dönüştürülemez ise ne olur?*<br>
    *Eğer elemanların dönüştürülemeyeceği bir tip verilirse NumPy **ValueError** adlı bir hata dönderir:*

***ValueError**: Python'da bir fonksiyona beklenmeyen veya yanlış bir tipte argüman girildiği zaman dönen hata türüdür.*

In [5]:
# integer olmayan bir string olan 'a' integer veri tipine dönüştürülemez.Hata mesajı dönderir.
import numpy as np
arr = np.array(['a', 3, 4, 5], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

## Var Olan Bir Dizinin Veri Tipini Dönüştürme 🧠	

ℹ️	*Var olan bir dizinin veri tipini değiştirmenin en iyi yolu, dizinin bir kopyasını oluşturan **astype()** metodunu kullanmaktır.*<br>
ℹ️	***astype()** fonksiyonu dizinin bir kopyasını oluşturur,ve veri tipini bir parametre olarak girmenize olanak sağlar*<br>
ℹ️	*Veri tipini belirtirken; float için **f**, integer için **i** vb. kullanabileceğiniz gibi direkt olarak **float**, **integer** şeklinde de parametre girebilirsiniz.*

In [6]:
# float veri tipinden integer veri tipine dönüşüm
import numpy as np
arr = np.array([3.14, 7.81, 11.13])

new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[ 3  7 11]
int32


*Aynı işlemi **int** parametresi kullanarak yapalım:*<br>

In [7]:
import numpy as np
arr = np.array([3.14, 7.81, 11.13])

new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)

[ 3  7 11]
int64


*Veri tipini integer'dan boolean'a dönüştürme:*

In [8]:
import numpy as np
arr = np.array([0,1,2,3])

new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[False  True  True  True]
bool
