# NumPy Dizilerinde Copy vs View 🚀	

## Copy ve View Arasındaki Farklılıklar 🧠	

ℹ️ ***copy** ve **view** arasındaki temel farklılık; **copy** yeni bir dizidir,**view** ise orijinal dizinin bir görünümüdür.*<br>
ℹ️ ***copy** kendi verisine sahiptir,ve kopya dizi üzerindeki herhangi bir değişiklik orijinal diziyi etkilemez,aynı şekilde orijinal dizi üzerindeki herhangi bir değişiklik yine kopya diziyi etkilemez.Birbirinden bağımsız birer nesnelerdir.*<br>
ℹ️ ***view**'in ise kendi verisi yoktur ve **copy**'nin aksine üzerinde yapılan değişiklikler orijinal dizinin durumunu etkiler.Orijinal dizi üzerindeki değişiklikler yine **view**'i etkiler.*

## COPY 🧠

💻 *Bir kopya oluşturalım,orijinal diziyi değiştirelim ve iki diziyi de ekrana bastıralım:*

In [1]:
import numpy as np
arr = np.array([2,3,4,5])
arr_copy = arr.copy()
arr[0] = 100
print(arr)
print(arr_copy)

[100   3   4   5]
[2 3 4 5]


⚠️ *Orijinal dizideki hiçbir değişiklik kopyalanmış diziyi etkilememelidir.* 

## VIEW 🧠	

💻	*Bir view oluşturalım,orijinal diziyi değiştirelim ve ikisini de ekrana bastıralım:*

In [2]:
import numpy as np
arr = np.array([11,12,13,14,15])
varr = arr.view()
arr[0] = 155
print(arr)
print(varr)

[155  12  13  14  15]
[155  12  13  14  15]


⚠️	*view orijinal dizideki değişikliklerden etkilenmelidir.Çünkü view orijinal diziyi referans alıyor.*

# View'de Değişiklikler Yapalım 🧠	

💻 *Bir view oluşturalın,view'de değişiklikler yapalım ve iki diziyi de ekrana bastıralım:*

In [3]:
import numpy as np
arr = np.array([10,20,30,40])
varr = arr.view()
varr[3] = -1
print(arr)
print(varr)

[10 20 30 -1]
[10 20 30 -1]


⚠️	*Orijinal dizi view'de yapılan değişikliklerden etkilenmelidir.*

## Dizinin Kendi Verisine Sahip Olup Olmadığını Kontrol Etme 🧠	

ℹ️	*Yukarıda bahsedildiği gibi, kopyalar kendi verisine sahiptir,view'lar ise kendi verisine sahip değildir.Peki nasıl kontrol edebiliriz?*<br>
ℹ️	*Her bir NumPy dizisi, kendi verisine sahip diziler için **None** değeri döndüren **base** özniteliğine sahiptir.*<br>
ℹ️	*Diğer bir deyişle **base** özniteliği orijinal diziyi ifade eder.*

*Bir dizinin kendi verisine sahip olup olmadığını kontrol etmek için **base** özniteliğini kullanalım:*

In [4]:
import numpy as np
arr = np.array([2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[2 3 4 5]


*Tanımda da bahsettiğimiz gibi copy() ile oluşturulmuş dizi nesnesi için None değeri döndü.view() ile oluşturduğumuz dizi nesnesi orijinal diziyi döndürdü.*