# NumPy Dizisini Yeniden Şekillendirme 🚀

## Dizileri Yeniden Şekillendirme 🧠

ℹ️ *Yeniden şekillendirmeden kasıt bir dizinin şeklini değiştirmektir.Yani boyutunu...*<br>
ℹ️ *Bir dizinin şekli her bir boyuttaki eleman sayısıdır.*<br>
ℹ️ *Yeniden şekillendirme yaparken boyut ekleme veya silme,her bir boyuttaki eleman sayısını değiştirme gibi birtakım işlemler gerçekleştirebiliriz.*

## 1 Boyutludan 2 Boyutluya Dönüştürme 🧠

*12 elemandan oluşan 1 boyutlu bir diziyi 2 boyutlu diziye dönüştürelim.Bu 2 boyutlu dizi her biri 3 elemandan oluşan 4 tane dizi içersin:*

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


*Yeni dizi her biri 3 elemanlı 4 tane alt diziden oluşuyor.Bir diğer deyişle 4x3'lük 2 boyutlu bir matris oluşturduk.* 🔥

## 1 Boyutludan 3 Boyutluya Dönüştürme 🧠

*20 elemandan oluşan tek boyutlu bir NumPy dizisini 3 boyutlu bir matrise dönüştürelim:*

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
new_arr = arr.reshape(2,5,2)
print(arr)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


*Yukarıdaki örnekte her biri 5x2'lik matris olan 2 elemanlı ve 3 boyutlu bir dizi oluşturduk.*	🔥

## Herhangi Bi Boyuta Dönüştürme Yapılabilir mi?	🧠

ℹ️ *Evet,dönüştürmek istediğimiz boyut ile halihazırda bulunan boyuttaki eleman sayısı birbiriyle örtüştüğü sürece bir boyuttan bir boyuta dönüştürme yapılabilir.*<br>
ℹ️ *Örnek vermek gerekirse: 1 boyutlu 8 elemanlı bir diziyi 2 satır 4 elemandan oluşan 2 boyutlu bir diziye dönüştürebiliriz fakat 3 satır 3 elemanlı yani 3x3'lük matrise dönüştüremeyiz çünkü bunun için 9 eleman gerekli.*

*8 eleman içeren 1 boyutlu diziyi 3x3'lük bir matrise dönüştürmeye çalışalım.Hata mesajı dönderecektir:*

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(3,3)
print(new_arr)

ValueError: cannot reshape array of size 8 into shape (3,3)

## Döndürülen Nesne Copy mi View mi?🧠

*Yeniden boyutlandırılan dizi nesnesinin copy mi view mi olduğunu kontrol edelim:*

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = arr.reshape(2,4)
print(new_arr)
print(new_arr.base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


📌*Yukarıdaki örnekte new_arr nesnesi 2 boyutlu bir matris ama base özniteliği orijinal diziyi dönderiyor.Yani bu bir view.*

## Bilinmeyen Boyut 🧠

ℹ️ *Bir adet bilinmeyen boyutunuz olabilir.*<br>
ℹ️ *Bu şu demek: **reshape()** metodunda boyutlardan biri için kesin bir sayı belirtmek zorunda olmadığınızdır.*<br>
ℹ️ *Değeri -1 olarak girin ve NumPy sizin için asıl girilmesi gereken numarayı hesaplasın.*

*1 boyutlu 12 elemanlı diziyi 2x3 elemanlı 3 boyutlu bir diziye dönüştürelim:*

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


*Görüldüğü üzere NumPy 2 tane 2x3'lük 3 boyutlu bir dizi oluşturdu.*

⚠️ *Sadece tek bir bilinmeyen boyut bilgisi verebiliriz.Birden fazla bilinmeyen boyut bilgisi hata mesajı dönmesine sebep olur:*

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
newarr = arr.reshape(2, -1, -1)
print(newarr)

ValueError: can only specify one unknown dimension

## Dizileri Düzleştirmek🧠

ℹ️ *Dizileri düzleştirmek:1'den büyüt boyuta sahip dizileri 1 boyutlu hale getirmek demektir.*<br>
ℹ️ *Bunu yapmak için **reshape(-1)** şeklinde bir kullanım vardır.*

*İki boyutlu bir diziyi tek boyutlu diziye dönüştürelim:*

In [7]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


📌 *NumPy'da boyut değiştirmeye yarayan **flatten**,**reval** gibi birden fazla fonksiyon vardır.Aynı zamanda elemanları yeniden düzenlemeye yardımcı olan **rot90**,**flip**,**fliplr** ve **flipud** gibi fonksiyonlar da mevcuttur.Bunlar NumPy'ın ileri seviye konularıdır.Daha sonra bunlara değineceğiz.*