# NumPy Dizi İterasyonu 🚀

ℹ️ *NumPy dizilerinde İterasyon,her bir elemanı tek tek incelemek,gözden geçirmek anlamına gelir.*<br>
ℹ️ *Numpy'da çok boyutlu dizilerle çalışırken bunu basit **for** döngüleriyle yapabiliriz.*<br>
ℹ️ *Tek boyutlu dizilerde iterasyon yapacaksak her bir elemanı atlamadan geçeceğiz demektir.*

*1 boyutlu dizide iterasyon işlemi:*

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


## 2 Boyutlu Dizilerde İterasyon 🧠

ℹ️ *İki boyutlu dizilerde her bir satırdaki her bir elemanı tek tek gezeriz:*

In [10]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


⚠️ *n boyutlu bir dizide iterasyon yaparken n-1'inci boyuta kadar iterasyon işlemi yaparız.*

ℹ️ *Asıl değerleri,skalerleri döndürmek için her bir boyut içerisindeki diziyi gezinmemiz gerekir:*

In [11]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
for i in arr:
    for x in i:
        print(x)
        

1
2
3
4
5
6


## 3 Boyutlu Dizilerde İterasyon 🧠

ℹ️ *3 boyutlu dizi içerisinde gezinme:*

In [12]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


*3 boyutlu dizimiz 2 elemanlı.2x3'lük 2 tane matrisimiz var.*

ℹ️ *Her bir skaleri,yani asıl değeri döndürmek for döngüsünü arttırmak gerekir*:

In [13]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
for i in arr:
    for x in i:
        for y in x:
            print(y)

1
2
3
4
5
6
7
8
9
10
11
12


## nditer() Kullanarak Dizilerde İterasyon İşlemi 🧠

ℹ️ ***nditer()** fonksiyonu çok basit iterasyonlardan çok gelişmiş iterasyonlara kadar iterasyon işlemi için bir yardımcı fonksiyondur.İterasyon işlemi sırasında karşımıza çıkan bazi basit sorunları çözmemize olanak sağlar.*

*3 boyutlu bir dizi için iterasyon işlemi gerçekleştirelim.*

In [15]:
import numpy as np
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Farklı Veri Tipleriyle Dizilerde İterasyon 🧠

ℹ️ *İterasyon işlemi sırasında elemanların veri tipini değiştirmek için beklenen veri tipini belirtmek adına **op_dtypes** argümanını kullanırız.*<br>
ℹ️ *NumPy, elemanların veri tipini yerinde(dizi elemanlarının olduğu alan) değiştirmez.Yukarıda bahsettiğimiz argümanı kullanabilmemiz için başka bir alan gereklidir.Bu ekstra alan **buffer** olarak adlandırılır ve **nditer()** içerisinde şu şekilde kullanılır : **flags = ['buffered']***

*Dizide string olarak iterasyon işlemi:*

In [17]:
import numpy as np
arr = np.array([1,2,3])
for i in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


## Farklı Adım Boyutuyla İterasyon İşlemi 🧠

ℹ️ *Filtreleme işleminden sonra iterasyon işlemi gerçekleştirebiliriz.*

*2 boyutlu dizide 1'er eleman atlayarak skalerleri gezinme işlemi:*

In [18]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
for i in np.nditer(arr[:, ::2]):
    print(i)

1
3
5
7


## ndenumerate() Kullanarak Numaralandırılmış İterasyon 🧠

ℹ️ *Burada sayma, birşeylerin numarasını birer birer belirtmek anlamına geliyor.*<br>
ℹ️ *Bazen iterasyon işlemi sırasında elemanların indeks bilgisine ihtiyaç duyabiliriz.ndenumerate() tam da bu ihtiyaç için kullanılıyor.*

In [21]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
for idx,i in np.ndenumerate(arr):
    print(idx,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7


*2 boyutlu dizilerde enumerate:*

In [22]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
for idx,i in np.ndenumerate(arr):
    print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
