# NumPy Dizilerini Birleştirme 🚀

ℹ️ *NumPy dizilerinde birleştirme,iki veya daha fazla dizinin içeriğini tek bir diziye yerleştirme olarak tanımlanabilir*<br>
ℹ️ *SQL'de tablolar anahtar(key) baz alınarak birleştirilir.NumPy dizilerinde birleştirme eksenler baz alınarak birleştirilir.*<br>
ℹ️ *Daha önce gördüğümüz **concatenate()** fonksiyonuna birleştirmek istediğimiz sıralı diziler eksen bilgisiyle birlikte argüman olarak girilir.Eğer eksen bilgisini girmez isek varsayılan olarak 0 değeri atanır.* 

In [2]:
# İki diziyi birleştirme işlemi
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print('Birleştirilmiş dizi:', arr)

Birleştirilmiş dizi: [1 2 3 4 5 6]


In [6]:
# 2 boyutlu dizilerde satır boyunca birleştirme
import numpy as np
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([[70,80,90], [100,110,120]])

arr = np.concatenate((arr1,arr2), axis = 1)
print( arr)

[[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]


In [7]:
# 2 boyutlu dizilerde sütun boyunca birleştirme
import numpy as np
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([[70,80,90], [100,110,120]])

arr = np.concatenate((arr1,arr2), axis = 0)
print( arr)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


## stack() Fonksiyonu Kullanarak Birleştirme 🧠

ℹ️ *Yığma birleştirme ile aynıdır,tek fark yığma işlemi yeni bir eksen üzerinde gerçekleştirilir.*<br>
ℹ️ *İki tane 1 boyutlu diziyi 2'nci bir eksen boyunca birleştirebiliriz;ki bu da onları üst üste yığmak,istiflemek anlamına gelir.*<br>
ℹ️ ***stack()** fonksiyonuna sıralı iki diziyi **axis** argümanıyla birlikte gireriz.axis değeri verilmediyse varsayılan olarak 0 değeri atanır.*

In [13]:
import numpy as np

arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])

arr = np.stack((arr1,arr2), axis = 0)
print(arr)

[[1 3 5]
 [2 4 6]]


*axis = 0 değeri girildiğinde stack() fonksiyonu dizileri olduğu gibi üst üste yığma işlemi gerçekleştiriyor.*

In [14]:
import numpy as np

arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])

arr = np.stack((arr1,arr2), axis = 1)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


*axis = 1 değeri girildiğinde stack() fonksiyonu aynı sütundaki elemanları tek bir satırda birleştirip son sütuna kadar istifliyor*

📌 *NumPy satır ve sütun boyunca yığma işlemlerini gerçekleştiren spesifik fonksiyonlara da sahiptir.*

## Satır Boyunca Yığma 🧠

ℹ️ *NumPy **hstack()** adlı dizileri satır boyunca istifleyen bir fonksiyon sağlar*

In [16]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


## Sutün Boyunca Yığma 🧠

ℹ️ *NumPy'da yine **vstack()** adında dizileri sütun boyunca istifleyen bir fonksiyona sahiptir*

In [17]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


## Derinlik Boyunca Yığma 🧠

ℹ️ ***dstack()** adlı NumPy fonksiyonu aynı derinliğe sahip dizileri yükseklik boyunca istifler.*<br>
ℹ️ *Önce dizileri 2 boyutlu hale getirir.Daha sonra 3.boyut yani derinlik ekseninde birleştirir.*

In [20]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
