# NumPy Dizilerinde Arama 🚀

ℹ️ *NumPy dizilerinde belirli bir değeri arayabilirsiniz.Geriye o değerle eşleşen indeks değeri döndürülür.*<br>
ℹ️ *Bir dizide arama işlemi gerçekleştirebilmek için **where()** fonksiyonu kullanılır.*

*Dizi içerisinde 4 değerini içeren indeks değerini döndürelim:*

In [15]:
import numpy as np
arr = np.array([1,2,3,4,4,5,6,7,4,9,4,11,12,9])

a = np.where(arr == 4)
print(a)

(array([ 3,  4,  8, 10]),)


*Yukarıdaki çıktının içerisinde array olan bir tuple nesnesi olduğunu görüyoruz.Çıktıya göre dizinin 3,4,8 ve 10.'uncu indekslerinde 4 değeri var.*

*Çift olan değerlerin indeks bilgilerini döndürelim:*

In [16]:
import numpy as np
arr = np.array([1,2,3,4,4,5,6,7,4,9,4,11,12,9])

a = np.where(arr % 2 == 0)
print(a)

(array([ 1,  3,  4,  6,  8, 10, 12]),)


*Tek olan değerlerin indeks bilgisini döndürelim:*

In [17]:
import numpy as np
arr = np.array([1,2,3,4,4,5,6,7,4,9,4,11,12,9])

a = np.where(arr % 2 != 0)
print(a)

(array([ 0,  2,  5,  7,  9, 11, 13]),)


## Search Sorted 🧠

ℹ️ ***searchsorted()** adlı bir fonksiyon var ve bu fonksiyon şu işlevi görüyor: binary search(ikili arama yapan) yapıyor ve arama sırasını korumak için eklenecek değerin indeks bilgisini döndürüyor.*<br>
ℹ️ *Yani elimizde sıralı bir dizi var,ekleyeceğimiz eleman öyle bir eleman olmalı ki dizinin sırasını bozmasın.Buna göre bu elemanın eklenmesi gereken yer bilgisini yani indeks bilgisini bize dönderiyor.*

In [18]:
import numpy as np
arr = np.array([5,6,7,8,9,10])
x = np.searchsorted(arr,7)
print(x)

2


ℹ️*fonksiyonumuz arama işlemine dizinin sol tarafından başlıyor ve 7 değerinin bir sonraki değerden büyük olmadığı ilk indeks değerini dönderiyor.*

*7 değerini 2'nci indeks değerinin yerine kolmalıyız ki sıra bozulmasın([5, 6, 7, 7, 8, 9, 10])*

## Sağ Taraftan Arama İşlemi🧠

ℹ️ *Varsayılan olarak fonksiyon en soldaki değeri dönderir.Fakat onun yerine *side = 'right'* parametresini vererek en sağdaki değeri de döndürebiliriz.*

In [19]:
import numpy as np
arr = np.array([5,6,7,8,9,10])
x = np.searchsorted(arr,7,side = 'right')
print(x)

3


ℹ️ *7 değeri sıralama düzenini bozmaması adına indeks değerinin 3 olduğu yere eklenmelidir.*<br>
ℹ️ *Fonksiyon arama işlemine sağ taraftan başlıyor ve 7 değerinin bir sonraki değerden küçük olmadığı ilk indeks değerini dönderiyor.*

## Çoklu Değerler 🧠

ℹ️ *Birden fazla değer için arama işlemi yaparken argüman olarak bir dizi verebiliriz:*

In [20]:
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


📌 *Çıktımız [1,2,3].Bu şu anlama geliyor : Ana dizimizde sıralama düzeninin bozulmaması için eklenecek değerlerin olması gereken indeks       değerleri sırayla 1,2,3'üncü indeks değerleri olmalıdır.Yani:*<br>
*2 elemanı için indeks değeri arr[1]*<br>
*4 elemanı için indeks değeri arr[2]*<br>
*6 elemanı için indeks değeri arr[3]*<br>
*olmalıdır ki arr dizisi sıralı bir dizi olarak kalsın.*>