# Dizilerde Sıralama 🚀

ℹ️ *Sıralama,dizideki elemanları sıralı bir şekilde yerleştirme işlemidir.*<br>
ℹ️ ***Sıralı dizi** demek nümerik veya alfabetik elemanların artan veya azalan sıraya göre bir sırada olması anlamını taşır.*
ℹ️ *NumPy dizi nesnesi **sort()** adlı belli bir diziyi argüman olarak alıp bu dizi elemanlarını sıralayan bir fonksiyona sahiptir.*

In [1]:
import numpy as np
arr = ([1,0,-5,10,3,2,5,7,8,9,6,5,3,1,4,3,7])
print(np.sort(arr))


[-5  0  1  1  2  3  3  3  4  5  5  6  7  7  8  9 10]


⚠️ ***sort()** fonksiyonu geri dönüş değeri olarak orijinal dizi nesnesinin kopyasını döndürür.Orijinal dizide bir değişiklik olmaz.*

ℹ️ *string türünde veya herhangi bir türde veri içeren bir diziyi de sıralayabiliriz:*

In [2]:
import numpy as np
arr = np.array(["Python","Java","R","C","TypeScript","Go"])
print(np.sort(arr))

['C' 'Go' 'Java' 'Python' 'R' 'TypeScript']


ℹ️ *Boolean türünde bir diziyi sıralayalım:*

In [3]:
import numpy as np
arr = np.array(["True", "False", "False"])
print(np.sort(arr))

['False' 'False' 'True']


## 2 Boyutlu Dizilerde Sıralama 🧠

ℹ️ *İki boyutlu dizilerde **sort()** fonksiyonu kullanılırsa,bütün alt diziler sıralı olarak döner.*

In [4]:
import numpy as np
arr = np.array([[1,0,2],[6,9,8]])
print(np.sort(arr))

[[0 1 2]
 [6 8 9]]
