# NumPy Dizi Filtreleme 🚀

## Dizi Filtreleme 🧠

ℹ️ *Mevcut bir diziden birtakım elemanlar çekip daha sonra bu çektiğimiz elemanlarla yeni bir dizi oluşturma işlemi **Filtreleme** olarak adlandırılır.*<br>
ℹ️ *NumPy'da **boolean indeksli liste** kullanarak bu filtreleme işlemi gerçekleştirilir.*

📌 ***Boolean inkdeksli liste**,boolean elemanlardan oluşan ve bu elemanların dizi indekslerine karşılık geldiği listelerdir.*

📌 *Eğer index değeri **True** ise o eleman filtrelenmiş diziye dahil olacak demektir.Eğer index değeri **False** ise o eleman filtrelenmiş dizinin dışına atılacak demektir.*

In [1]:
# Sadece index 0 ve index 2 değerlerinden oluşan bir dizi oluşturalım
import numpy as np
arr = np.array([20,40,30,42])
x = [True,False,True,False]

new_arr = arr[x]
print(new_arr)

[20 30]


*Yukarıdaki örnekte booelan indeksli listedeki **True** değerlere karşılık gelen elemanları çektik ve yeni diziye atadık.*

## Filtrelenmiş Dizi Oluşturma 🧠

*Birazdan yapacağımız örnek,genel olarak filtreleme işleminde tercih edilen bir yöntemle olacak.*

In [2]:
# 42 değerinden büyük değerleri içeren bir filtre dizisi oluşturalım:

import numpy as np
arr = np.array([41,42,43,44])

# Boş filtre dizisi oluşturalım
filter_arr = []

# arr dizisindeki elemanları tek tek iterate ediyoruz
for element in arr:
    # Eğer eleman değeri 42'den büyükse filter_arr nesnesine eleman olarak True eklenecek
    if element > 42:
        filter_arr.append(True)
    # Eğer eleman değeri 42'den küçük veya eşitse o elemean filtre dizisine False olarak eklenecek
    else:
        filter_arr.append(False)

new_arr = arr[filter_arr]
print(new_arr)

[43 44]


*Bir örnek daha yapalım.Bu sefer sadece çift elemanları döndüren bir filtre dizisi oluşturalım:*

In [3]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

# Boş filtre dizisi
filter_arr = []

# Dizi içerisinde dolaşma
for element in arr:
    # Eğer eleman değeri 2'ye tam bölünürse filtre dizisine True değeri eklenecek
    if element % 2 == 0:
        filter_arr.append(True)
    # Eğer eleman değeri 2'ye bölünmüyorsa filtre dizisine bu False değeri olarak eklenecek
    else:
        filter_arr.append(False)

new_arr = arr[filter_arr]
print(new_arr)

[ 0  2  4  6  8 10]


## Direkt Olarak Dizi Üzerinden Filtreleme 🧠

ℹ️ *Yukarıdaki örnekler NumPy'da oldukça yaygın bir şekilde  kullanılıyor ve mücadele etmek için güzel bir yol.*<br>
ℹ️ *Fakat böyle şartlı döngüler kullanmak yerine diziyi direkt olarak ikame edebiliriz ve beklediğimiz bir şekilde çalışır.*

In [4]:
# 32'den büyük elemanları çekelim ve boş diziye filtreleme yoluyla atayalım
import numpy as np
arr = np.array([30,31,32,33,34,35])
filter_arr = arr > 32
new_arr = arr[filter_arr]
print(new_arr)

[33 34 35]


In [5]:
# Çift olan elemanları yeni diziye eleman olarak ekleyelim
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr % 2 == 0
new_arr = arr[filter_arr]
print(new_arr)

[ 2  4  6  8 10]
