# NumPy'da Random Sayılar 🚀

## Random Sayı Nedir? 🧠

ℹ️ *Buradaki random sayı her seferinde farklı bir sayı anlamına gelmiyor.Rastgelenin buradaki asıl anlamı mantıksal olarak tahmin edilemez sayılardır.*<br>

## Pseudo(Sözde) Random ve True(Gerçek) Random 🧠

ℹ️ *Bilgisayarlar programlar üzerinde çalışır.Programlar ise komut setleridir.Yani burada rastgele sayı üreten bazı algoritmalar olması gerektiği anlamına gelir.*<br>
ℹ️ *Eğer random sayılar üretebilen bir program var ise,bu tahmin edilebilirdir.Bu nedenle gerçek anlamda rastgele değildir.*<br>
ℹ️ *Random sayılar **pseudo random** adında bir yaratma algoritması ile üretilirler.*<br>
ℹ️ *Peki gerçek anlamda rastgele sayılar üretebilir miyiz?*<br>
ℹ️ *Evet.Bilgisayarlarımızda Gerçek anlamda rastgele sayılar üretebilmemiz için bazı dış kaynaklardan rastgele veri elde etmemiz gerekiyor.Bu dış kaynak genellikle klavye tuş vuruşu,fare hareketleri,ağ verileri gibi veriler olabilir.*<br>
ℹ️ *Güvenlikle(şifreleme anahtarları) veya rastgelelik tabanlı uygulamalar(rulet çarkı gibi) geliştirmeyeceğimiz sürece gerçek rastgele sayılara ihtiyaç yoktur.*<br>
ℹ️ *Bu bölümde sadece sözde rastgele sayılar kullanacağız.

## Random Sayı Üretimi 🧠

ℹ️ *NumPy random sayılarla çalışmamız için **random** adında bir modül sunar*

In [1]:
# 0-100 arasında rastgele sayı üretimi
from numpy import random
x = random.randint(100)
print(x)

85


## Random Float Üretimi🧠

ℹ️ ***rand()** adındaki bu random fonksiyonu bize 0 ile 1 arasında bir değer döndürür.*

In [2]:
from numpy import random
x = random.rand()
print(x)

0.07623116478369041


## Rastgele Dizi Üretimi 🧠

ℹ️ *NumPy'da dizilerle çalıştığımızı söylemiştik.Rastgele dizi üretimi için aşağıdaki örneklerde kullanılan iki metod bulunmaktadır:*

### integers 

ℹ️ *randint() metodu dizi boyutunu spesifik olarak belirtirken  size parametresi alır:*

In [3]:
# 5 elemanlı,0-100 arasında sayılardan oluşan bir dizi üretelim
from numpy import random
arr = random.randint(100,size = 5)
print(arr)

[65 80 16 84 28]


In [4]:
# 2x3 boyutlu 0-100 sayıları arasında elemanlara sahip 2 boyutlu dizi(matris) üretimi
from numpy import random
arr = random.randint(100,size = (2,3))
print(arr)

[[37 75 59]
 [33 86 62]]


### float

ℹ️ *dizi boyutunu belirtirken **rand()** metodunu kullanabiliriz:*

In [5]:
# 5 random float değerinden oluşan dizi üretimi
from numpy import random
arr = random.rand(5)
print(arr)

[0.72026319 0.09319491 0.85484821 0.15558342 0.06999602]


In [6]:
# random float değerlerinden oluşan 3x5'lik matris üretimi
from numpy import random
arr = random.rand(3,6)
print(arr)

[[0.1084357  0.75113586 0.15789866 0.88527736 0.19187682 0.85583719]
 [0.12303802 0.37868825 0.83149771 0.21316734 0.67560674 0.76021648]
 [0.03645131 0.80492383 0.99411702 0.53896675 0.18143872 0.52639911]]


## Bir Diziden Rastgele Sayı Üretimi 🧠

ℹ️ ***choice()** medodu var olan bir diziyi referans alarak rastgele bir eleman üretmenizi sağlar.*<br>
ℹ️ ***choice()** metodu diziyi argüman olarak alır,ve dizi içerisinden rastgele bir eleman seçip geri dönüş değeri olarak döndürür.*

In [7]:
from numpy import random
x = random.choice([1,3,5,6,7,9])
print(x)

6


ℹ️ ***choice()** metodu size değerlerden oluşan bir dizi nesnesi de döndürebilir*.<br>
ℹ️ ***size** parametresi dizinin boyutu olarak girilir.*

In [8]:
# argüman olarak girilen dizi parametrelerinden oluşan 2 boyutlu bir dizi oluşturma
from numpy import random
x = random.randint([1,3,5,7,9], size = (3,5))
print(x)

[[0 1 1 4 4]
 [0 1 0 1 3]
 [0 2 3 3 4]]
