# Rastgele Veri Dağılımı 🚀

ℹ️ *Rastgele Dağılım,bütün olası değerlerin her bir değerin ne sıklıkla ortaya çıktığının bir listesidir.*<br>
ℹ️ *Böyle listeler İstatistik ve Veri Bilimi alanlarında çok önemli bir yere sahiptir.*<br>
ℹ️ ***random** modülü rastgele üretilmiş veri dağılımları döndüren metodlar sunar.*

## Rastgele Dağılım 🧠

ℹ️ *Rastgele dağılım belli bir olasılık yoğunluk fonksiyonunu izleyen rastgele sayılar kümesidir.*<br>

📌 ***Olasılık Dağılım Fonksiyonu**: Sürekli olasılığı ifade eder.Örnek:Bir dizide bulunan bütün değerlerin olasılığı.*

ℹ️ ***random** modülünde bulunan **choice()** metodunu kullanarak tanımlanmış olasılıklara bağlı rastgele sayılar üretebiliriz.*<br>
ℹ️ ***choice()** metodu her bir değer için bize bir olasılık değeri sunar*<br>
ℹ️ *Bu olasılık değerleri 0 ile 1 arasındadır.0'ın anlamı değer asla gerçekleşmeyecektir.1 değeri ise değer her zaman ortaya çıkacaktır anlamına gelir.*

*Bütün bu anlattıklarımızı bir örnek üzerinden detaylı bir şekilde anlatalım:*

*Her bir değerin 3,5,7 ve 9 rakamlarından oluştuğu 100 elemanlı 1 boyutlu bir dizi üretelim.*<br>
*3 değerinin olma olasılığı 0.1*<br>
*5 değerinin olma olasılığı 0.3*<br>
*7 değerinin olma olasılığı 0.6*<br>
*9 değerinin olmas olasılığı 0.0*<br>

In [1]:
from numpy import random

arr = random.choice([3,5,7,9], p = [0.1, 0.3, 0.6, 0.0], size = 100)
print(arr)

[3 5 5 7 5 5 7 7 7 3 7 3 5 7 3 5 5 3 3 5 5 3 7 5 7 7 5 7 7 5 5 5 7 5 7 7 7
 5 7 7 5 7 7 7 7 3 5 5 7 3 7 7 7 5 7 7 5 5 7 5 7 7 5 5 7 7 5 5 7 5 7 7 5 7
 7 5 7 7 3 3 7 7 7 7 3 7 5 5 5 7 3 7 5 7 5 7 3 5 7 7]


⚠️ *Bütün olasılık değerlerinin toplamı her zaman 1 olmalıdır.*

📌 *Yukarıda yazmış olduğumuz kodu 100 defa dahi çalıştırsak bile 9 değeri asla oluşmayacaktır.*<br>
📌 ***size** parametresi ile 2 boyutlu dizi döndürebileceğimizi görmüştük.Yukarıdaki örneği 2 boyutlu diziye uyarlayalım.*

In [2]:
# Yukarıdaki örnek ile aynı fakat bu sefer 3x5 elemanlı 2 boyutlu dizi üretmiş olacağız.
from numpy import random
arr = random.choice([3,5,7,9], p = [0.1, 0.3, 0.6, 0.0], size = (3,5))
print(arr)

[[7 7 7 7 7]
 [7 7 5 5 7]
 [5 5 7 5 7]]
